name: server ci/cd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.yml 파일 만들기
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build --stacktrace

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/emotionbot/tobe

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            # 로그 디렉터리 생성 및 권한 설정
            sudo mkdir -p /home/ec2-user/log
            sudo chown ubuntu:ubuntu /home/ec2-user/log

            # 기존 실행 중인 앱 종료 및 새 버전 배포
            rm -rf /home/ubuntu/emotionbot/current
            mkdir /home/ubuntu/emotionbot/current
            mv /home/ubuntu/emotionbot/tobe/project.jar /home/ubuntu/emotionbot/current/project.jar
            cd /home/ubuntu/emotionbot/current
            sudo fuser -k -n tcp 8080 || true

            # 애플리케이션 실행
            nohup java -Duser.timezone=Asia/Seoul -jar project.jar > ./output.log 2>&1 &

            # 임시 폴더 정리
            rm -rf /home/ubuntu/emotionbot/tobe
